### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by jlc13360** [remycrochon/home-assistant#1]
Bonjour,

comment définissez-vous les paramètres items_classes des flexbox dans vos différentes pages? Je ne trouve rien qui me permette de comprendre quelles valeurs utiliser. Merci.

**Comment by remycrochon** [comment]
Bonjour
Désolé, j'ai rien trouvé non plus, je l'ai fait en tatonnant par exemple   "items_classes: 'col-xs-12 col-sm-12 col-sm-12 col-md-24' affiche sur une colonne. Je pensais le demander à Dwain mais j'ai pas encore fait. Peut etre un début de réponse dans http://flexboxgrid.com/.

**Comment by jlc13360** [comment]
Bonjour,

Pas de raison d'être désolé. Merci pour la réponse. Au vu de votre tableau
de bord ou tout est nickel... Je vais donc tâtonner moi aussi.
